apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebeat-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/filebeat"